define({
    "root": {
        "loading": "Loading",
        "overview": "Overview",
        "library": "Library",
        "clients": "Clients",
        "client": "Client",
        "settings": "Settings",
        "date": "Date",
        "event": "Event",
        "books": "Tools",
        "book": "Tool",
        "book_new": "Add Tool",
        "books_search": "Search tools in library",
        "rentals": "Rentals",
        "rentals_search": "Search for rentals",
        "rentals_new": "New Rental",
        "rentals_details": "Rental Details",
        "renter": "Renter",
        "return_date": "Return Date",
        "rent": "Rent",
        "save": "Save",
        "reset": "Reset",
        "delete": "Delete",
        "details": "Details",
        "history": "History",
        "jpg_only": "Only jpg images",
        "title": "Title",
        "title_ph": "Tool title",
        "author": "Author",
        "author_ph": "Tool author",
        "editor": "Editor",
        "editor_ph": "Tool editor",
        "publisher": "Publisher",
        "publisher_ph": "Tool publisher",
        "country": "Country",
        "country_ph": "Publication country",
        "language": "Language",
        "language_ph": "Tool language",
        "edition": "Edition",
        "edition_ph": "Tool edition",
        "year": "Year",
        "year_ph": "Year of publication",
        "isbn_ph": "Tool ISBN code",
        "pages": "Pages",
        "pages_ph": "Tool total pages",
        "quantity": "Quantity",
        "quantity_ph": "Total amount of this tool",
        "status": "Status",
        "available": "Available",
        "not_available": "Not Available",
        "price": "Price",
        "price_ph": "Tool price",
        "clients_search": "Search for clients",
        "client_add": "Add Client",
        "name": "Name",
        "name_ph": "Client full name",
        "address": "Address",
        "address_ph": "Client address",
        "phone": "Phone",
        "phone_ph": "Client phone number",
        "email": "Email",
        "email_ph": "Client email address",
        "city": "City",
        "city_ph": "Client city",
        "new_password": "New Password",
        "about": "About",
        "new_member": "New User",
        "member_details": "User Details",
        "version": "Version",
        "developer": "Developer",
        "rental_success_save": "Rental successfully saved",
        "rental_error_save": "Error saving rental",
        "rental_success_del": "Rental successfully deleted",
        "rental_error_del": "Error deleting rental",
        "book_success_save": "Tool successfully saved",
        "book_error_save": "Error saving tool",
        "book_success_del": "Tool successfully deleted",
        "book_error_del": "Error deleting tool",
        "client_success_save": "Client successfully saved",
        "client_error_save": "Error saving client",
        "client_success_del": "Client successfully deleted",
        "client_error_del": "Error deleting client",
        "user_success_save": "User successfully saved",
        "user_error_save": "Error saving user",
        "user_success_del": "User successfully deleted",
        "user_error_del": "Error deleting user",
        "events": ["rent", "sell"],
        "countries": {
            AF: "Afghanistan",
            AL: "Albania",
            DZ: "Algeria",
            AS: "American Samoa",
            AD: "Andorra",
            AO: "Angola",
            AI: "Anguilla",
            AQ: "Antarctica",
            AG: "Antigua and Barbuda",
            AR: "Argentina",
            AM: "Armenia",
            AW: "Aruba",
            AU: "Australia",
            AT: "Austria",
            AZ: "Azerbaijan",
            BS: "Bahamas",
            BH: "Bahrain",
            BD: "Bangladesh",
            BB: "Barbados",
            BY: "Belarus",
            BE: "Belgium",
            BZ: "Belize",
            BJ: "Benin",
            BM: "Bermuda",
            BT: "Bhutan",
            BO: "Bolivia",
            BA: "Bosnia and Herzegovina",
            BW: "Botswana",
            BV: "Bouvet Island",
            BR: "Brazil",
            IO: "British Indian Ocean Territory",
            BN: "Brunei Darussalam",
            BG: "Bulgaria",
            BF: "Burkina Faso",
            BI: "Burundi",
            KH: "Cambodia",
            CM: "Cameroon",
            CA: "Canada",
            CV: "Cape Verde",
            KY: "Cayman Islands",
            CF: "Central African Republic",
            TD: "Chad",
            CL: "Chile",
            CN: "China",
            CX: "Christmas Island",
            CC: "Cocos (Keeling) Islands",
            CO: "Colombia",
            KM: "Comoros",
            CG: "Congo",
            CD: "Congo, the Democratic Republic of the",
            CK: "Cook Islands",
            CR: "Costa Rica",
            CI: "Cote D'Ivoire",
            HR: "Croatia",
            CU: "Cuba",
            CY: "Cyprus",
            CZ: "Czech Republic",
            DK: "Denmark",
            DJ: "Djibouti",
            DM: "Dominica",
            DO: "Dominican Republic",
            EC: "Ecuador",
            EG: "Egypt",
            SV: "El Salvador",
            GQ: "Equatorial Guinea",
            ER: "Eritrea",
            EE: "Estonia",
            ET: "Ethiopia",
            FK: "Falkland Islands (Malvinas)",
            FO: "Faroe Islands",
            FJ: "Fiji",
            FI: "Finland",
            FR: "France",
            GF: "French Guiana",
            PF: "French Polynesia",
            TF: "French Southern Territories",
            GA: "Gabon",
            GM: "Gambia",
            GE: "Georgia",
            DE: "Germany",
            GH: "Ghana",
            GI: "Gibraltar",
            GR: "Greece",
            GL: "Greenland",
            GD: "Grenada",
            GP: "Guadeloupe",
            GU: "Guam",
            GT: "Guatemala",
            GN: "Guinea",
            GW: "Guinea-Bissau",
            GY: "Guyana",
            HT: "Haiti",
            HM: "Heard Island and Mcdonald Islands",
            VA: "Holy See (Vatican City State)",
            HN: "Honduras",
            HK: "Hong Kong",
            HU: "Hungary",
            IS: "Iceland",
            IN: "India",
            ID: "Indonesia",
            IR: "Iran, Islamic Republic of",
            IQ: "Iraq",
            IE: "Ireland",
            IL: "Israel",
            IT: "Italy",
            JM: "Jamaica",
            JP: "Japan",
            JO: "Jordan",
            KZ: "Kazakhstan",
            KE: "Kenya",
            KI: "Kiribati",
            KP: "Korea, Democratic People's Republic of",
            KR: "Korea, Republic of",
            KW: "Kuwait",
            KG: "Kyrgyzstan",
            LA: "Lao People's Democratic Republic",
            LV: "Latvia",
            LB: "Lebanon",
            LS: "Lesotho",
            LR: "Liberia",
            LY: "Libyan Arab Jamahiriya",
            LI: "Liechtenstein",
            LT: "Lithuania",
            LU: "Luxembourg",
            MO: "Macao",
            MK: "Macedonia, the Former Yugoslav Republic of",
            MG: "Madagascar",
            MW: "Malawi",
            MY: "Malaysia",
            MV: "Maldives",
            ML: "Mali",
            MT: "Malta",
            MH: "Marshall Islands",
            MQ: "Martinique",
            MR: "Mauritania",
            MU: "Mauritius",
            YT: "Mayotte",
            MX: "Mexico",
            FM: "Micronesia, Federated States of",
            MD: "Moldova, Republic of",
            MC: "Monaco",
            MN: "Mongolia",
            MS: "Montserrat",
            MA: "Morocco",
            MZ: "Mozambique",
            MM: "Myanmar",
            NA: "Namibia",
            NR: "Nauru",
            NP: "Nepal",
            NL: "Netherlands",
            AN: "Netherlands Antilles",
            NC: "New Caledonia",
            NZ: "New Zealand",
            NI: "Nicaragua",
            NE: "Niger",
            NG: "Nigeria",
            NU: "Niue",
            NF: "Norfolk Island",
            MP: "Northern Mariana Islands",
            NO: "Norway",
            OM: "Oman",
            PK: "Pakistan",
            PW: "Palau",
            PS: "Palestinian Territory, Occupied",
            PA: "Panama",
            PG: "Papua New Guinea",
            PY: "Paraguay",
            PE: "Peru",
            PH: "Philippines",
            PN: "Pitcairn",
            PL: "Poland",
            PT: "Portugal",
            PR: "Puerto Rico",
            QA: "Qatar",
            RE: "Reunion",
            RO: "Romania",
            RU: "Russian Federation",
            RW: "Rwanda",
            SH: "Saint Helena",
            KN: "Saint Kitts and Nevis",
            LC: "Saint Lucia",
            PM: "Saint Pierre and Miquelon",
            VC: "Saint Vincent and the Grenadines",
            WS: "Samoa",
            SM: "San Marino",
            ST: "Sao Tome and Principe",
            SA: "Saudi Arabia",
            SN: "Senegal",
            CS: "Serbia and Montenegro",
            SC: "Seychelles",
            SL: "Sierra Leone",
            SG: "Singapore",
            SK: "Slovakia",
            SI: "Slovenia",
            SB: "Solomon Islands",
            SO: "Somalia",
            ZA: "South Africa",
            GS: "South Georgia and the South Sandwich Islands",
            ES: "Spain",
            LK: "Sri Lanka",
            SD: "Sudan",
            SR: "Suriname",
            SJ: "Svalbard and Jan Mayen",
            SZ: "Swaziland",
            SE: "Sweden",
            CH: "Switzerland",
            SY: "Syrian Arab Republic",
            TW: "Taiwan, Province of China",
            TJ: "Tajikistan",
            TZ: "Tanzania, United Republic of",
            TH: "Thailand",
            TL: "Timor-Leste",
            TG: "Togo",
            TK: "Tokelau",
            TO: "Tonga",
            TT: "Trinidad and Tobago",
            TN: "Tunisia",
            TR: "Turkey",
            TM: "Turkmenistan",
            TC: "Turks and Caicos Islands",
            TV: "Tuvalu",
            UG: "Uganda",
            UA: "Ukraine",
            AE: "United Arab Emirates",
            GB: "United Kingdom",
            US: "United States",
            UM: "United States Minor Outlying Islands",
            UY: "Uruguay",
            UZ: "Uzbekistan",
            VU: "Vanuatu",
            VE: "Venezuela",
            VN: "Viet Nam",
            VG: "Virgin Islands, British",
            VI: "Virgin Islands, U.S.",
            WF: "Wallis and Futuna",
            EH: "Western Sahara",
            YE: "Yemen",
            ZM: "Zambia",
            ZW: "Zimbabwe"
        },
        "error_required": "{0} is required",
        "error_acceptance": '{0} must be accepted',
        "error_min": '{0} must be greater than or equal to {1}',
        "error_max": '{0} must be less than or equal to {1}',
        "error_range": '{0} must be between {1} and {2}',
        "error_length": '{0} must be {1} characters',
        "error_minLength": '{0} must be at least {1} characters',
        "error_maxLength": '{0} must be at most {1} characters',
        "error_rangeLength": '{0} must be between {1} and {2} characters',
        "error_oneOf": '{0} must be one of: {1}',
        "error_equalTo": '{0} must be the same as {1}',
        "error_digits": '{0} must only contain digits',
        "error_number": '{0} must be a number',
        "error_email": '{0} must be a valid email',
        "error_url": '{0} must be a valid url',
        "error_inlinePattern": '{0} is invalid'
    },
    'it-it': true
});