define({
    "loading": "Caricamento",
    "overview": "Panoramica",
    "library": "Libreria",
    "clients": "Clienti",
    "client": "Cliente",
    "settings": "Settaggi",
    "date": "Data",
    "event": "Evento",
    "books": "Libri",
    "book": "Libro",
    "book_new": "Nuovo Libro",
    "books_search": "Cerca libri",
    "rentals": "Noleggi",
    "rentals_search": "Cerca noleggi",
    "rentals_new": "Nuovo Noleggio",
    "rentals_details": "Dettagli Noleggio",
    "renter": "Noleggiatore",
    "return_date": "Data Rientro",
    "rent": "Noleggia",
    "save": "Salva",
    "reset": "Resetta",
    "delete": "Elimina",
    "details": "Dettagli",
    "history": "Archivio",
    "jpg_only": "Solo immagini jpg",
    "title": "Titolo",
    "title_ph": "Titolo libro",
    "author": "Autore",
    "author_ph": "Autore libro",
    "editor": "Redattore",
    "editor_ph": "Redattore libro",
    "publisher": "Editore",
    "publisher_ph": "Editore libro",
    "country": "Paese",
    "country_ph": "Paese di pubblicazione",
    "language": "Lingua",
    "language_ph": "Lingua del libro",
    "edition": "Edizione",
    "edition_ph": "Edizione del libro",
    "year": "Anno",
    "year_ph": "Anno di pubblicazione",
    "isbn_ph": "Codice ISBN del libro",
    "pages": "Pagine",
    "pages_ph": "Pagine totali del libro",
    "quantity": "Quantità",
    "quantity_ph": "Quantità totale in magazzino",
    "status": "Stato",
    "available": "Disponibile",
    "not_available": "Non Disponibile",
    "price": "Prezzo",
    "price_ph": "Prezzo del libro",
    "clients_search": "Cerca clienti",
    "client_add": "Nuovo Cliente",
    "name": "Nome",
    "name_ph": "Nome del cliente",
    "address": "Indirizzo",
    "address_ph": "Indirizzo del cliente",
    "phone": "Telefono",
    "phone_ph": "Numero di telefono del cliente",
    "email": "Email",
    "email_ph": "Indirizzo email del cliente",
    "city": "Città",
    "city_ph": "Città del cliente",
    "new_password": "Nuova Password",
    "about": "Informazioni",
    "new_member": "Nuovo Utente",
    "member_details": "Dettagli Utente",
    "version": "Versione",
    "developer": "Sviluppatore",
    "rental_success_save": "Noleggio salvato con successo",
    "rental_error_save": "Errore nel salvataggio del noleggio",
    "rental_success_del": "Noleggio eliminato con successo",
    "rental_error_del": "Errore nell'eliminazione del noleggio",
    "book_success_save": "Libro salvato con successo",
    "book_error_save": "Errore nel salvataggio del libro",
    "book_success_del": "Libro eliminato con successo",
    "book_error_del": "Errore nell'eliminazione del libro",
    "client_success_save": "Cliente salvato con successo",
    "client_error_save": "Errore nel salvataggio del cliente",
    "client_success_del": "Cliente cancellato con successo",
    "client_error_del": "Errore nella cancellazione del cliente",
    "user_success_save": "Utente salvato con successo",
    "user_error_save": "Errore nel salvataggio dell'utente",
    "user_success_del": "Utente cancellato con successo",
    "user_error_del": "Errore nella cancellazione dell'utente",
    "events": ["noleggio", "vendita"],
    "error_required": "{0} è obbligatorio",
    "error_acceptance": '{0} deve essere accettato',
    "error_min": '{0} deve essere maggiore o uguale a {1}',
    "error_max": '{0} deve essere minore o uguale a {1}',
    "error_range": '{0} deve essere tra {1} e {2}',
    "error_length": '{0} deve essere di {1} caratteri',
    "error_minLength": '{0} deve essere almeno di {1} caratteri',
    "error_maxLength": '{0} deve essere al massimo di {1} caratteri',
    "error_rangeLength": '{0} deve essere tra {1} e {2} caratteri',
    "error_oneOf": '{0} deve essere uno di: {1}',
    "error_equalTo": '{0} deve essere lo stesso di {1}',
    "error_digits": '{0} deve contenere solo numeri',
    "error_number": '{0} deve essere un numero',
    "error_email": '{0} deve essere una email valida',
    "error_url": '{0} deve essere un url valido',
    "error_inlinePattern": '{0} non è valido'
});